### ISSUE TITLE
RangeError: Index out of range

### ISSUE THREAD

**Issue by janispritzkau** [Fan7asy/Multiogar-Unlimited#1]
When I try to connect to the server via http://agar.io/?ip=localhost:447 the server crashes and I get this error:
```
C:\Users\Janis\Desktop\Multiogar-Unlimited\src\index.js:36
    throw new TypeError(err.stack);
    ^

TypeError: RangeError: Index out of range
    at checkOffset (buffer.js:934:11)
    at Buffer.readDoubleLE (buffer.js:1127:5)
    at Reader.readDouble (C:\Users\Janis\Desktop\Multiogar-Unlimited\src\packet\Reader.js:50:34)
    at Handler.processMouse (C:\Users\Janis\Desktop\Multiogar-Unlimited\src\packet\Handler.js:90:24)
    at Handler.process (C:\Users\Janis\Desktop\Multiogar-Unlimited\src\packet\Handler.js:110:14)
    at Player.updateTick (C:\Users\Janis\Desktop\Multiogar-Unlimited\src\Player.js:185:29)
    at Server.updateClients (C:\Users\Janis\Desktop\Multiogar-Unlimited\src\Server.js:467:36)
    at Server.mainLoop (C:\Users\Janis\Desktop\Multiogar-Unlimited\src\Server.js:1216:14)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at process.<anonymous> (C:\Users\Janis\Desktop\Multiogar-Unlimited\src\index.js:36:11)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:329:26)
```

**Comment by Fan7asy** [comment]
Oh sorry I've forgotten to mention in the readme, that this server only supports protocol v4.
I would recommend using [my client](https://github.com/Fan7asy/Client) .
